CREATE TABLE FOREX (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`SYMBOL` VARCHAR(50) NOT NULL,
	`TICK_DATE` DATETIME NOT NULL,
	`OPEN` DOUBLE NOT NULL DEFAULT '0',
	`HIGH` DOUBLE NOT NULL DEFAULT '0',
	`LOW` DOUBLE NOT NULL DEFAULT '0',
	`CLOSE` DOUBLE NOT NULL DEFAULT '0',
	`VOLUME` DOUBLE NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);
