ALTER TABLE article
PARTITION BY HASH (YEAR(DATE_TIME)*100 + MONTH(DATE_TIME))
PARTITIONS 10;

ALTER TABLE article_word
PARTITION BY HASH (ARTICLE_ID)
PARTITIONS 20;

CREATE OR REPLACE VIEW article_day_view AS
SELECT a.*, DATE(DATE_ADD(CONVERT_TZ(DATE_SUB(a.DATE_TIME, INTERVAL 1 HOUR), 'UTC', 'US/Eastern'),INTERVAL '14:30' HOUR_MINUTE)) AS DATE_DAY
FROM article a;

CREATE OR REPLACE VIEW wordcount_view AS
SELECT a.DATE_DAY AS DATE_TIME, aw.WORD AS WORD, COUNT(aw.WORD) AS WORD_COUNT, COUNT(DISTINCT A.ID) AS DOCUMENT_COUNT
FROM article_day_view AS a
JOIN article_word aw ON aw.ARTICLE_ID = a.ID
GROUP BY aw.WORD, a.DATE_DAY
ORDER BY a.DATE_DAY ASC, COUNT(aw.WORD) DESC;

DROP TABLE IF EXISTS wordcount_view_table;

CREATE TABLE wordcount_view_table AS    
SELECT * FROM wordcount_view;